# Generated by Django 3.1.5 on 2021-02-24 11:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('participants', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='audio_book.audio')),
            ],
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_of_title', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audiobook', to='audio_book.audio')),
            ],
        ),
    ]
