# Generated by Django 3.1.5 on 2021-02-25 05:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_book', '0003_audio_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
